name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version-file: 'go.mod'
      - name: Setup go-swagger
        run: |
          dir=$(mktemp -d)
          git clone https://github.com/go-swagger/go-swagger "$dir" 
          cd "$dir"
          go install ./cmd/swagger
      # - name: fmt
      #   run: make fmt-check
      - name: Generate provider
        run: make generate
      - name: Run tests
        run: make test
      - name: Publish
        uses: goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757 # v3.2.0
        with:
          version: latest
          args: build --snapshot --rm-dist
      - name: Upload artifact
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
        with:
          name: providers
          path: dist/*
